### ISSUE TITLE
Is this still supported?

### ISSUE THREAD

**Issue by SchneiderCode** [microsoft/pxt-react-extension-template#2]
Hello @pelikhan  ,

I've been working on trying to get the demo template working with MakeCode but have been unable to do so without it crashing. The issue appears to be related to how the iframe is sandboxed in MakeCode. This template utilizes forms, but MakeCode's iframe does not appear to allow for form submissions. I've done some quick edits to remove the forms and use standard html buttons, and that works locally but does not work with the online MakeCode editor. 

Before diving deeper into the template's code and doing further testing, I wanted to make sure if the features in this iframe extension are still supported by the MakeCode editor (transferring Serial communication, reading from and writing to the user's code).

**Comment by pelikhan** [comment]
I am afraid this kind of extension is not supported for 3rd party anymore so your extension will not load in the online editor.

________________________________

**Comment by SchneiderCode** [comment]
Thanks for the quick response. Are there other options for incorporating 3rd party UI's into MakeCode?  Or is this not a route MakeCode is looking at supporting at all?

**Comment by pelikhan** [comment]
I am afraid this is not planned for now. I would recommend posting on forum.MakeCode.com about it.

________________________________

**Comment by SchneiderCode** [comment]
Will do, thanks!
